theme: jekyll-theme-minimal
titles_from_headings:
  enabled: false
description: The Insight Loop cuts your stories in half. Facilitate this free 1/2-day workshop for your devs!
logo: /img/deep-roots-logo.png
show_downloads: false
author:
  twitter: digdeeproots
twitter:
  username: digdeeproots
